import { Role } from "@prisma/client";

/**
 * Flat permission-key registry. Every module route declares the key(s) it needs
 * via requirePermission(). New modules add their own keys here — never invent
 * ad-hoc strings inline in a route file.
 */
export const PERMISSIONS = {
  IDENTITY_REGION_CONFIGURE: "identity.region.configure",
  IDENTITY_USER_MANAGE: "identity.user.manage",
  IDENTITY_PERMISSION_OVERRIDE_MANAGE: "identity.permission_override.manage",

  SALES_CATALOG_VIEW: "sales.catalog.view",
  SALES_CATALOG_MANAGE: "sales.catalog.manage",
  SALES_CATALOG_APPROVE: "sales.catalog.approve",

  SALES_LEAD_VIEW: "sales.lead.view",
  SALES_LEAD_CREATE: "sales.lead.create",
  SALES_LEAD_REASSIGN: "sales.lead.reassign",
  SALES_LEAD_COMMENT: "sales.lead.comment",

  SALES_CUSTOMER_VIEW: "sales.customer.view",
  SALES_CUSTOMER_CREATE: "sales.customer.create",

  SALES_OPPORTUNITY_VIEW: "sales.opportunity.view",
  SALES_OPPORTUNITY_CREATE: "sales.opportunity.create",
  SALES_OPPORTUNITY_REASSIGN: "sales.opportunity.reassign",
  SALES_OPPORTUNITY_WIN: "sales.opportunity.win",
  SALES_OPPORTUNITY_COMMENT: "sales.opportunity.comment",

  SALES_QUOTATION_VIEW: "sales.quotation.view",
  SALES_QUOTATION_CREATE: "sales.quotation.create",
  SALES_QUOTATION_APPROVE: "sales.quotation.approve",
  SALES_QUOTATION_APPROVE_OVERRIDE: "sales.quotation.approve.override",

  SALES_AMC_VIEW: "sales.amc.view",
  SALES_PROJECT_VIEW: "sales.project.view",

  SALES_REPORT_VIEW_REGION: "sales.report.view.region",
  SALES_REPORT_VIEW_CROSS_REGION: "sales.report.view.cross_region",

  SALES_QUERY_VIEW: "sales.query.view",
  SALES_QUERY_CREATE: "sales.query.create",
  SALES_QUERY_UPDATE: "sales.query.update",
  SALES_QUERY_ASSIGN_DEPARTMENT: "sales.query.assign_department",
  SALES_QUERY_REASSIGN_OWNER: "sales.query.reassign_owner",
  SALES_QUERY_STATUS_TRANSITION: "sales.query.status_transition",
  SALES_QUERY_COMMENT: "sales.query.comment",
  SALES_QUERY_COMMENT_MODERATE: "sales.query.comment.moderate",
  SALES_QUERY_ATTACHMENT_UPLOAD: "sales.query.attachment.upload",
  SALES_QUERY_FOLLOWUP_MANAGE: "sales.query.followup.manage",
  SALES_QUERY_FOLLOWUP_VIEW: "sales.query.followup.view",
  SALES_REPORT_EXPORT: "sales.report.export",
  SALES_DASHBOARD_VIEW: "sales.dashboard.view",

  DEPARTMENT_MANAGE: "department.manage",

  NOTIFICATION_VIEW: "notification.view",

  PICKLIST_MANAGE: "picklist.manage",
} as const;

export type PermissionKey = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

/**
 * Default permission set per role, seeded into RolePermission (Section 3.2 matrix).
 * Ownership scoping ("own" leads/opportunities for Sales Executive, "team" for
 * Sales Manager) is NOT encoded here — it's enforced in the service layer against
 * resource.ownerId / owner.reportingToId, so the permission key stays reusable.
 */
export const ROLE_DEFAULT_PERMISSIONS: Record<Role, PermissionKey[]> = {
  [Role.SUPER_ADMIN]: Object.values(PERMISSIONS),
  [Role.REGIONAL_ADMIN]: [
    PERMISSIONS.IDENTITY_USER_MANAGE,
    PERMISSIONS.IDENTITY_PERMISSION_OVERRIDE_MANAGE,
    PERMISSIONS.SALES_CATALOG_VIEW,
    PERMISSIONS.SALES_CATALOG_APPROVE,
    PERMISSIONS.SALES_LEAD_VIEW,
    PERMISSIONS.SALES_LEAD_CREATE,
    PERMISSIONS.SALES_LEAD_REASSIGN,
    PERMISSIONS.SALES_LEAD_COMMENT,
    PERMISSIONS.SALES_CUSTOMER_VIEW,
    PERMISSIONS.SALES_CUSTOMER_CREATE,
    PERMISSIONS.SALES_OPPORTUNITY_VIEW,
    PERMISSIONS.SALES_OPPORTUNITY_CREATE,
    PERMISSIONS.SALES_OPPORTUNITY_REASSIGN,
    PERMISSIONS.SALES_OPPORTUNITY_WIN,
    PERMISSIONS.SALES_OPPORTUNITY_COMMENT,
    PERMISSIONS.SALES_QUOTATION_VIEW,
    PERMISSIONS.SALES_QUOTATION_CREATE,
    PERMISSIONS.SALES_QUOTATION_APPROVE,
    PERMISSIONS.SALES_QUOTATION_APPROVE_OVERRIDE,
    PERMISSIONS.SALES_AMC_VIEW,
    PERMISSIONS.SALES_PROJECT_VIEW,
    PERMISSIONS.SALES_REPORT_VIEW_REGION,
    PERMISSIONS.SALES_QUERY_VIEW,
    PERMISSIONS.SALES_QUERY_CREATE,
    PERMISSIONS.SALES_QUERY_UPDATE,
    PERMISSIONS.SALES_QUERY_ASSIGN_DEPARTMENT,
    PERMISSIONS.SALES_QUERY_REASSIGN_OWNER,
    PERMISSIONS.SALES_QUERY_STATUS_TRANSITION,
    PERMISSIONS.SALES_QUERY_COMMENT,
    PERMISSIONS.SALES_QUERY_COMMENT_MODERATE,
    PERMISSIONS.SALES_QUERY_ATTACHMENT_UPLOAD,
    PERMISSIONS.SALES_QUERY_FOLLOWUP_VIEW,
    PERMISSIONS.SALES_QUERY_FOLLOWUP_MANAGE,
    PERMISSIONS.SALES_DASHBOARD_VIEW,
    PERMISSIONS.SALES_REPORT_EXPORT,
    PERMISSIONS.DEPARTMENT_MANAGE,
    PERMISSIONS.NOTIFICATION_VIEW,
    PERMISSIONS.PICKLIST_MANAGE,
  ],
  [Role.SALES_MANAGER]: [
    PERMISSIONS.SALES_CATALOG_VIEW,
    PERMISSIONS.SALES_LEAD_VIEW,
    PERMISSIONS.SALES_LEAD_CREATE,
    PERMISSIONS.SALES_LEAD_REASSIGN,
    PERMISSIONS.SALES_LEAD_COMMENT,
    PERMISSIONS.SALES_CUSTOMER_VIEW,
    PERMISSIONS.SALES_CUSTOMER_CREATE,
    PERMISSIONS.SALES_OPPORTUNITY_VIEW,
    PERMISSIONS.SALES_OPPORTUNITY_CREATE,
    PERMISSIONS.SALES_OPPORTUNITY_REASSIGN,
    PERMISSIONS.SALES_OPPORTUNITY_WIN,
    PERMISSIONS.SALES_OPPORTUNITY_COMMENT,
    PERMISSIONS.SALES_QUOTATION_VIEW,
    PERMISSIONS.SALES_QUOTATION_CREATE,
    PERMISSIONS.SALES_QUOTATION_APPROVE,
    PERMISSIONS.SALES_AMC_VIEW,
    PERMISSIONS.SALES_PROJECT_VIEW,
    PERMISSIONS.SALES_REPORT_VIEW_REGION,
    PERMISSIONS.SALES_QUERY_VIEW,
    PERMISSIONS.SALES_QUERY_CREATE,
    PERMISSIONS.SALES_QUERY_UPDATE,
    PERMISSIONS.SALES_QUERY_ASSIGN_DEPARTMENT,
    PERMISSIONS.SALES_QUERY_REASSIGN_OWNER,
    PERMISSIONS.SALES_QUERY_STATUS_TRANSITION,
    PERMISSIONS.SALES_QUERY_COMMENT,
    PERMISSIONS.SALES_QUERY_COMMENT_MODERATE,
    PERMISSIONS.SALES_QUERY_ATTACHMENT_UPLOAD,
    PERMISSIONS.SALES_QUERY_FOLLOWUP_VIEW,
    PERMISSIONS.SALES_QUERY_FOLLOWUP_MANAGE,
    PERMISSIONS.SALES_DASHBOARD_VIEW,
    PERMISSIONS.NOTIFICATION_VIEW,
  ],
  [Role.SALES_EXECUTIVE]: [
    PERMISSIONS.SALES_CATALOG_VIEW,
    PERMISSIONS.SALES_LEAD_VIEW,
    PERMISSIONS.SALES_LEAD_CREATE,
    PERMISSIONS.SALES_LEAD_COMMENT,
    PERMISSIONS.SALES_CUSTOMER_VIEW,
    PERMISSIONS.SALES_CUSTOMER_CREATE,
    PERMISSIONS.SALES_OPPORTUNITY_VIEW,
    PERMISSIONS.SALES_OPPORTUNITY_CREATE,
    PERMISSIONS.SALES_OPPORTUNITY_WIN,
    PERMISSIONS.SALES_OPPORTUNITY_COMMENT,
    PERMISSIONS.SALES_QUOTATION_VIEW,
    PERMISSIONS.SALES_QUOTATION_CREATE,
    PERMISSIONS.SALES_AMC_VIEW,
    PERMISSIONS.SALES_PROJECT_VIEW,
    PERMISSIONS.SALES_REPORT_VIEW_REGION,
    PERMISSIONS.SALES_QUERY_VIEW,
    PERMISSIONS.SALES_QUERY_CREATE,
    PERMISSIONS.SALES_QUERY_UPDATE,
    PERMISSIONS.SALES_QUERY_STATUS_TRANSITION,
    PERMISSIONS.SALES_QUERY_COMMENT,
    PERMISSIONS.SALES_QUERY_ATTACHMENT_UPLOAD,
    PERMISSIONS.SALES_QUERY_FOLLOWUP_VIEW,
    PERMISSIONS.SALES_QUERY_FOLLOWUP_MANAGE,
    PERMISSIONS.SALES_DASHBOARD_VIEW,
    PERMISSIONS.NOTIFICATION_VIEW,
  ],
  [Role.AUDITOR]: [
    PERMISSIONS.SALES_CATALOG_VIEW,
    PERMISSIONS.SALES_LEAD_VIEW,
    PERMISSIONS.SALES_CUSTOMER_VIEW,
    PERMISSIONS.SALES_OPPORTUNITY_VIEW,
    PERMISSIONS.SALES_QUOTATION_VIEW,
    PERMISSIONS.SALES_AMC_VIEW,
    PERMISSIONS.SALES_PROJECT_VIEW,
    PERMISSIONS.SALES_REPORT_VIEW_REGION,
    PERMISSIONS.SALES_QUERY_VIEW,
    PERMISSIONS.SALES_QUERY_FOLLOWUP_VIEW,
    PERMISSIONS.SALES_DASHBOARD_VIEW,
    PERMISSIONS.NOTIFICATION_VIEW,
  ],
};

// Roles that see all regions without a region_id filter (Super Admin, or an
// explicitly granted cross-region override — see effectivePermissions.ts).
export const CROSS_REGION_ROLES: Role[] = [Role.SUPER_ADMIN];

// Approval limits per role — SM-3.5, Section 4.3 example table. Configurable
// per region later via a config table; hard-coded defaults for now.
export const APPROVAL_LIMITS: Record<
  Role,
  { maxValue: number; maxDiscountPct: number } | null
> = {
  [Role.SALES_EXECUTIVE]: { maxValue: 50_000, maxDiscountPct: 5 },
  [Role.SALES_MANAGER]: { maxValue: 500_000, maxDiscountPct: 15 },
  [Role.REGIONAL_ADMIN]: { maxValue: 5_000_000, maxDiscountPct: 25 },
  [Role.SUPER_ADMIN]: null, // unlimited
  [Role.AUDITOR]: null, // never approves
};
